enthought/chaco

- CHANGES.txt
- chaco/tools/better_zoom.py
- chaco/tools/tests/better_zoom_test_case.py
Fixes #240.
The problem occurred when the tool was added with keyboard focus on the component and the mouse in the region where the tool was working.  A keyboard interaction with the tool would then give a traceback because `position` was not defined.
> Add default position and tests for BetterZoom

- CHANGES.txt
- chaco/base.py
- chaco/tests/base_utils_test_case.py
Replace `bin_search` with a `numpy.searchsorted`-based algorithm. This gives a 5x speedup, but keeps the results the same (unit tests should all pass).
Also use `column_stack` instead of `zip` in `arg_find_runs`.  This is slightly slower in typical use cases, but up to 10x faster in bad cases (large arrays with many separate runs).  As part of this, added tests for `arg_find_runs` and the `flat` argument, since this is what is actually used in practice in a lot of chaco code.
> Speed-ups for chaco.base

- CHANGES.txt
- chaco/image_plot.py
- chaco/image_utils.py
- chaco/tests/test_image_plot.py
- chaco/tests/test_image_utils.py
- examples/demo/image_plot_origin_and_orientation.py
While adding some plotting capabilities to an `ImagePlot` subclass (see https://github.com/enthought/geolibs/pull/43), I ended up having to refactor `ImagePlot` quite a bit.
This PR cleans up some of the coordinate transforms in `ImagePlot` and fixes an issue with negative screen sizes (see https://github.com/enthought/enable/issues/109). I've also added tests, but I'm not sure how robust this testing is: It requires precise pixel positions in the rendered image. (This positioning is achieved using a tweaked index grid, tweaked plot bounds, and slicing some "extra" rows/columns off the rendered image. Probably a bit fragile :P)
> Refactor image plot

- chaco/scales/tests/test_time_scale.py
- chaco/scales/time_scale.py
This PR fixes a couple of long-standing bugs in the ticking code for time axes.
* The first should fix the selection of tick times for day of month and month of year, which had timezone issues.
* The second fixes the _tests_ for the time_scale module, which worked if you ran them with a computer set to UTC, but otherwise probably not.
* Adds versions of certain interesting tests which simulate running the code in non-UTC timezones, in particular timezones with non-whole-hour offsets.
For the PR reviewer: Chaco's time scale handling works internally in seconds since the Unix Epoch, but displays and selects ticks according to those times in the current timezone.
There are likely many other issues with the time scale code, but this at least allows us to run the tests cleanly and …
> Fix timescale tests and calendar timescales

- chaco/tools/better_selecting_zoom.py
- chaco/tools/tests/range_zoom_test_case.py
There is a small problem with the better_selecting_zoom... The range zoom is opaque... This is caused by setting the alpha on the range zoom before the the color is set... Overriding the alpha property.
I did a small refactoring so that the code for setting the fill color is now the same for both the box zoom and range zoom.
> Issue with range zoom being an opaque color

- examples/demo/advanced/spectrum.py
While running on OS X, the `spectrum.py` demo will occasionally crash inside PyAudio with `IOError: [Errno Input overflowed] -9981`.  This patch simply restarts the audio stream if that happens.
> FIX: Spectrum demo occasionally crashes with IOError

- chaco/contour_line_plot.py
- chaco/contour_poly_plot.py
- chaco/plot.py
- chaco/tests_with_backend/create_2d_test_case.py
- examples/demo/basic/contour_plot.py
Fixes #310 amongst other issues.
This PR fixes a number of issues with contour plots, and expands their capabilities:
* allows grid points to be non-uniformly sampled x and y values (ie. not a linspace)
* allows regions to be masked out
* treats non-finite values as being masked
* fixes assumption in `Plot` code that x and y values for index must be linearly spaced
* distinguishes between 2d data plotted at vertices and 2d data plotted in cells in `Plot` code
* significant simplifications in code paths by avoiding having to handle off-by-one errors in various places.
> Fix contour plot grids

- setup.py
I received the following error when trying to build from the source 4.6.0 tarball obtained from
https://github.com/enthought/chaco/releases/download/4.6.0/chaco-4.6.0.tar.gz
```
File "setup.py", line 133, in <module>
write_version_py()
File "setup.py", line 113, in write_version_py
match = re.match(r'.*?\.dev(?P<dev_num>\d+)', full_v)
NameError: name 'full_v' is not defined
```
This PR fixes the variable names in this section of setup.py.
Not 100% certain if it should be `full_version` or `fullversion`, but I went with the latter as that is what seemed to be used in the other cases.
(Alternately, deleting chaco/_version.py also allows the build to proceed by avoiding this section of setup.py)
> fix variable names for building from source distribution

- setup.py
Some installations of git have `~` expansions in their global `gitconfig` files. `git` processes need to have the `HOME` environment variable defined.
This fix will need to be propagated to other `setup.py` files that reuse this code.
> BUG: Copy over HOME value to git environment.

- setup.py
Release 4.6.1
This supersedes https://github.com/enthought/chaco/pull/340 which was my earlier, unfinished attempt at releasing 4.6.1. As that PR was closed without merging and no tags were created for 4.6.1, I decided to re-use the version number (rather than jump straight to 4.6.2).
> Release 4.6.1

- chaco/tests/test_ticks.py
We dropped this a while back but a stray `unittest2` import found its way in with the merge of a long-lived PR.
> MAINT: Remove stray usage of unittest2.

- chaco/color_bar.py
Closes #311. The `arange` produced an empty array when the `direction` attribute is set to `flipped` since `mapper.low_pos > mapper.high_pos`. This PR tells `arange` to descend when using the `flipped` direction rather than ascend. Here is the example from #311 before:
and after:
> FIX: missing color bar when direction flipped

- chaco/axis.py
- chaco/base.py
- chaco/data_label.py
- chaco/label_axis.py
- chaco/legend.py
- chaco/log_mapper.py
- chaco/multi_array_data_source.py
- chaco/polygon_plot.py
- chaco/scatterplot.py
- chaco/tests/test_array_or_none.py
- chaco/text_plot_1d.py
- chaco/tools/lasso_selection.py
- chaco/tools/range_selection.py
- chaco/tools/tests/range_selection_test_case.py
Fixes all of the instances of ```FutureWarning: comparison to `None` will result in an elementwise object comparison in the future.``` that I could find.
Additionally clean up a few warnings so that we have a clean test suite.
> Use ArrayOrNone

- chaco/api.py
- chaco/data_frame_plot_data.py
- chaco/tests/data_frame_plot_data_test_case.py
- ci/edmtool.py
- ci/requirements.txt
- examples/demo/basic/pandas_data.py
- examples/demo/demo.cfg
- travis-ci-requirements.txt
This is for you, @jonathanrocher. It needs a bit more testing around 'index' and an example.
> FEAT: Add DataFramePlotData.

- chaco/tests/test_image_plot.py
This updates the computation of the root-mean square function (used in tests to compare generated images with the expectation) to use int_ instead of blanket 64-bit. This came up because the result of the upcast is fed into `np.bincount`, which on 32-bit Windows will raise a `TypeError` for 64-bit inputs.
> MAINT: Upcast to int_ instead of int64 to avoid bincount issue.

- CHANGES.txt
- chaco/tools/dataprinter.py
- docs/source/sphinxext/comment_eater.py
- docs/source/sphinxext/compiler_unparse.py
- docs/source/sphinxext/docscrape.py
- docs/source/sphinxext/docscrape_sphinx.py
- docs/source/sphinxext/numpydoc.py
- docs/source/sphinxext/traitsdoc.py
To get the docs build back on the rails (#380), I reverted the Python 2/3 compatibility layer from https://github.com/enthought/chaco/pull/369 for the Sphinx extensions (the rest of the compatibility layer is still in place). I began by updating the import statements to match what Sphinx expects, but even after doing this I found that some of the six constructs didn't play well with the rest of the code. As this code is old and will not work on Python 3 without some serious maintenance (#324), I decided to just roll back that part of the code.
closes #380
> MAINT: Get docs to build again

- CHANGES.txt
- chaco/scales/safetime.py
@corranwebster This is your fix from https://github.com/enthought/chaco/issues/376. Can you give this a quick look?
> FIX: Avoid initializing EPOCH from t = 0.

- CHANGES.txt
- chaco/scales/safetime.py
- chaco/tests/test_image_plot.py
- chaco/tools/dataprinter.py
- docs/source/sphinxext/comment_eater.py
- docs/source/sphinxext/compiler_unparse.py
- docs/source/sphinxext/docscrape.py
- docs/source/sphinxext/docscrape_sphinx.py
- docs/source/sphinxext/numpydoc.py
- docs/source/sphinxext/traitsdoc.py
Same as https://github.com/enthought/chaco/pull/389 but cherry-picking merge commits only.
> Backports for 4.7.1 release

- examples/demo/advanced/data_cube.py
Fixes the `advanced/data_cube.py` demo, which passed multiple arguments to the `on_trait_change` decorator instead of a comma-separated string.
> FIX: Use single comma-separated trait names in on_trait_change, not multiple arguments

- CHANGES.txt
- chaco/tools/scatter_inspector.py
- chaco/tools/tests/scatter_inspector_test_case.py
- examples/demo/basic/scatter_inspector.py
Goal: I am building connected scatter plots and wanted to propagate hover and selection events from one plot to the other. Selection events can be propagated by listener to the tool's component's index's metadata_changed, but that's very labor intensive. And there was no way to propagate hover events.
This PR fixes both these issues, by proposing to emit custom `ScatterInspectorEvent`, which holds information about the type of event, and the scatter point index being involved. The logic is:
* a `select` type event gets emitted on selection and a different `deselect` event gets emitted when deselecting a point.
* a single `hover` event gets emitted when hovering a point (no event if the mouse moves while on the same point)
* a `hover` event gets emitted when mouse leaves a point, with …
> Feature: scatter inspector event

- chaco/array_plot_data.py
- Add `see also` section in docstring of `set_data` pointing to `update_data` (since I always forget its name). 
- Replace copy-pasta docstring in `update_data` by something more accurate.
> Tweak: docstring for ArrayPlotData.set_data and ArrayPlotData.update_data

- chaco/tools/legend_highlighter.py
Before, the `LegendHighlighter` tool would respond to mouse clicks even if the legend was not visible.
> FIX: Respect visibility in the LegendHighlighter

- chaco/tools/legend_highlighter.py
- examples/demo/multiaxis.py
A Legend can have multiple plot renderers per name.
> FIX: Handle multiple plots in LegendHighlighter

- chaco/tools/lasso_selection.py
> FIX: Pass a C-contiguous array to points_in_polygon

- chaco/polygon_plot.py
- chaco/tools/lasso_selection.py
Ahem... Right. So, in #409, I said there was one other call to `points_in_polygon`, but it looked OK. Well, I was wrong. It was being called with a transposed input. This corrects that.
> FIX: Ensure contiguous inputs to points_in_polygon

- CHANGES.txt
- chaco/errorbar_plot.py
- chaco/plot.py
- chaco/polygon_plot.py
- chaco/tests/errorbarplot_test_case.py
- chaco/tests/plot_test_case.py
- chaco/tools/lasso_selection.py
- chaco/tools/legend_highlighter.py
- examples/demo/multiaxis.py
- setup.py
This cherry-picks the following PRs into the 4.7.x release branch: #394, #401, #402, #403, #409, #410
> Release 4.7.2

- chaco/tests/data_frame_plot_data_test_case.py
This PR adds pandas DataFramePlotData skip if pandas package does not exist.
Closes #392
> ENH: skip DataFramePlotData tests if pandas is not installed

- chaco/quiverplot.py
Do not render quiver if there are no points to draw.
Fixes #414
> FIX: do not render quiver if there is no point

- examples/demo/advanced/spectrum.py
Fixes issue where NumPy doesn't accept float values to define shapes, to index, or to slice by replacing the true divisions with floor divisions (`//`) when dividing the number of samples by 2.
```python
File "spectrum.py", line 186, in <module>
popup = Demo()
File "spectrum.py", line 172, in __init__
self.plot = _create_plot_component(self.controller)
File "spectrum.py", line 41, in _create_plot_component
empty_amplitude = zeros(NUM_SAMPLES/2)
TypeError: 'float' object cannot be interpreted as an integer
```
> Fix float indices in Spectrum demo

- .travis.yml
https://blog.travis-ci.com/2018-11-19-required-linux-infrastructure-migration
> MAINT: Remove sudo flag

- examples/demo/basic/scatter_inspector2.py
... to show how to combine a `ScatterInspector` with a `TextOverlay`.
> Doc: second scatter inspector example

- chaco/text_plot_1d.py
This is a nice little feature that I implemented for another project and wanted to port here as well. This PR adds options to align the label in the index direction (either left/center/right or top/center/bottom depending on orientation). There were already options for this sort of thing in the non-index direction but there was no way to do it in the index direction.
Screenshot with toy plot showing the new possible positioning: left/center/right or top/center/bottom (previously the label was always placed where the blue letters are)
> Add option for aligning label in index direction in TextPlot1D

- chaco/scales/tests/test_scales.py
- chaco/shell/tests/test_tutorial_example.py
- chaco/tests/test_array_plot_data.py
Import `unittest` from the standard library instead of importing it from `traits`.
> Update unittest imports

- chaco/label_axis.py
It is possible to specify a rotation angle for the labels of a `LabelAxis` to be any value: they don't have to be multiples of 90 and the comment is wrong. 
For example, this is what I am getting with 30:
> Remove erroneous comment about label_rotation of LabelAxis.

- chaco/tools/dataprinter.py
Goal is to mirror what was done in `ImageInspectorOverlay` in #431 for consistency and educational purposes.
(Few more tweaks to make the file pep8 compliant.)
> Refactor DataPrinter to add _build_text_from_event method

- chaco/barplot.py
- chaco/errorbar_plot.py
This is a drive-by fix for `DeprecationWarning` messages seen in the output of the test suite of a Chaco-using project.
> Fix two uses of the deprecated Logger.warn method.

- chaco/api.py
Adds missing imports of SegmentPlot and TextPlot to `api.py`.
> FIX: Missing imports of SegmentPlot and TextPlot

- chaco/function_image_data.py
- chaco/layers/status_layer.py
- chaco/layers/svg_range_selection_overlay.py
- chaco/overlays/container_overlay.py
- chaco/overlays/coordinate_line_overlay.py
- chaco/overlays/databox.py
- chaco/selectable_legend.py
- chaco/shell/commands.py
- chaco/shell/plot_maker.py
- chaco/shell/scaly_plot.py
- chaco/tests/test_default_colormaps.py
- chaco/toolbar_plot.py
- chaco/tools/dataprinter.py
- chaco/tools/draw_points_tool.py
- chaco/tools/highlight_tool.py
- chaco/tools/image_inspector_tool.py
- chaco/tools/lasso_selection.py
- chaco/tools/legend_highlighter.py
- chaco/tools/line_inspector.py
- chaco/tools/line_segment_tool.py
- chaco/tools/range_selection.py
- chaco/tools/range_selection_overlay.py
- chaco/tools/regression_lasso.py
- chaco/tools/save_tool.py
- chaco/tools/tracking_pan_tool.py
- chaco/tools/traits_tool.py
- chaco/transform_color_mapper.py
- chaco/ui/popupable_plot.py
Import directly from the module where each class is implemented instead of importing from `chaco.api`.
> FIX: Circular imports in toolbar_plot and transform_color_mapper

- chaco/tools/tests/test_range_selection.py
`test_selection_no_warning` is checking that Chaco itself doesn't raise any warnings on selection assignment. Previously, we were filtering out a known NumPy warning; that filter doesn't work with NumPy 1.16.x because the warning message changed.
This PR updates the filter to filter out all warning messages from packages other than Chaco.
Fixes #468.
> Fix a test that fails with NumPy 1.16.x.

- CHANGES.txt
- setup.py
This time this has all the necessary changes ;-)
I've double-checked that tests pass in a new (Python 3.7) environment. There are some deprecation warnings (ticketed in #475) that should be looked at but aren't urgent. While testing, I also ran into https://github.com/enthought/enable/issues/360, which was tricky to get round (my home machine runs Arch Linux, which doesn't ship with swig-3 any longer).
@mdickinson This is the follow-up from https://github.com/enthought/chaco/pull/472
> REL: 4.8.0

- examples/demo/advanced/scalar_image_function_inspector.py
The changes introduced in this PR allow me to run the script and interact with the GUI.
I haven't looked into why previously the grid spacing in y was commented out and why the grid spacing in x was used when calculating the y grid.
closes #357
> Fix a chaco example script

- chaco/horizon_plot.py
- chaco/linear_mapper.py
- chaco/tests/test_linearmapper.py
This PR fixes an obvious bug in the `LinearMapper` code, where we attempt to look up the `shape` attribute of a list or a tuple.
Code ref: https://github.com/enthought/chaco/blob/e0e4f7d8bc5551191ad65295fe97f55190e87a9c/chaco/linear_mapper.py#L47-L50
> Fix attempts to get the .shape attribute of a list or tuple.

- .travis.yml
- appveyor.yml
- ci/install-edm-linux.sh
- ci/install-edm-osx.sh
- install-edm-windows.cmd
Update edm to the latest version (2.0.0). This PR fixes the CI issue seen in PR #489 related to invalid metadata in eggs.
> Update edm and install/config scripts

- chaco/base_1d_plot.py
- chaco/tests/test_line_scatterplot.py
- chaco/tests/test_plot.py
- chaco/tests/test_scatterplot_1d.py
- chaco/tests/test_text_plot_1d.py
- chaco/tests/text_plot_test_case.py
Adds a `index_range` property, synonym of `index_mapper.range`, to `Base1DPlot`. This corresponds to a similarly defined property in `Base2DPlot`, and `Plot._handle_range_changed()` expects this attribute to exist in order to work properly.
\+ new assertions for regression testing.
Closes #490
> Add missing property index_range to 1D plots

- examples/demo/functionplotter.py
> Do not expose 'auto' for infinite series

- chaco/contour/cntr.c
Fixes #475 
`PyArray_FromDims` was removed in Numpy 1.18 (see https://github.com/numpy/numpy/pull/14100).
> MAINT: Remove uses of PyArray_FromDims

- examples/demo/financial_plot_dates.py
> Limit the min zoom out factor along x axis to prevent date range error

- examples/demo/basic/bar_plot_stacked.py
> Fix stacked bar plot example, by using the correct starting_value

- examples/demo/financial/correlations.py
- examples/demo/financial/stock_prices.py
- examples/demo/shell/dates.py
Fix zoomout issues in examples financial/correlations.py, financial/stock_prices.py, shell/dates.py
Fixes #415  (the ones mentioned in the comment)
> Fix zoomout issues 

- chaco/base_contour_plot.py
closes #466. Also reported in #359.
Fixed by requesting redraw when index mapper is updated in contour plots.
> Fix: Zoom not working with contour plots

- examples/user_guide/plot_types/plot_window.py
For safety against future Traits internal refactors, import from traits.api whenever possible.
> Import from traits.api instead of from traits.has_traits

- examples/demo/multiaxis.py
- Aligned j0, j2 and j3's `value_mapper` so curves are correctly placed. To some extent, that changes a bit the purpose of the example to be more like the kind of thing that's scientifically useful (as opposed to disconnecting 4 plot's y mappers, but only displaying 2 axis).
- Added axis titles to clarify where to read y-values.
- Added a zoom tool because it is tricky to do and universally needed.
- pep8 fixes.
> Fix and clean up multiaxis.py example

- chaco/plot_factory.py
- chaco/tests/test_plot_factory.py
These factory functions are used all over the place in the demos. This PR adds:
1. docstrings for the factory functions.
2. unit tests for the factory functions.
3. a `**renderer_traits` argument to support passing more renderer traits through the factory.
Even though my eyes bleed, I am refraining from adding pep8 fixes to keep the PR clean.
> Feature: support renderer traits

- docs/Makefile
Adds doc2dash flags to:
- set the online redirect url (`-u`) so one can go from the local docsets to the online ones.
- Set the index page (`-I`) to show `index.html`, which is what is showed online, instead of the index of all the names.
> ENH: Setup online redirect and proper index page for docset

- .travis.yml
- appveyor.yml
- chaco/shell/plot_window.py
- ci/edmtool.py
as it says on the tin.
Note: this means that we effectively don't test with wxpython and pyside any more. 
@rahulporuri Do you know of any other toolkits that are supported under Python 3.6?
> Remove Python 2.7, 3.5 testing, add PyQt 5

- ci/edmtool.py
Applying a quick fix for [Command names with underscores must be invoked with dashes instead when upgrading from 6.7 to 7.0](https://github.com/pallets/click/issues/1123)
This will make the documentation command consistent:
https://github.com/enthought/chaco/blob/192675d6cb579df56458b87988026d895e7a7a84/ci/edmtool.py#L44
> FIX: Enforce underscore for click command

- .travis.yml
- chaco/__init__.py
- ci/edmtool.py
fixes #522
This PR adds a `--source` click option and uses this option on cron jobs to install other ets packages from source.
Note that previously enable was installed from source always and that was how traits, traitsui and pyface got installed.  Following Marks comment here: https://github.com/enthought/envisage/pull/325#issuecomment-713410126, I added all of these to `__requires__` in `__init__.py`.  Additionally, I made it so that by default enable is not installed from source, but it will be when the `--source` flag is used.  
This follows what is done in other ets projects (e.g https://github.com/enthought/envisage/blob/8245931f7e3dfcb6513bfb7dc2ae9b10ca6f89a1/etstool.py#L255-L273)
> Add source click option used on cron jobs to install ets packages from source

- ci/edmtool.py
fixes #533 
This PR makes the exact same change that was made in https://github.com/enthought/envisage/pull/326 to solve the same issue.  It adds the -W default flag.
> TST: Switch on default warning flag for CI test command

- .travis.yml
- appveyor.yml
- ci/edmtool.py
fixes #536 
Also fixes #527 
In this PR we try to install pyside2 from edm instead of pip.  In order to do so, we need to use the latest version of edm in CI, so those version numbers are bumped as well.
In retrospect these should've been two separate PRs (shame!) and if a reviewer would prefer I am happy to go back and split them.  Initially I was just trying to fix 536 without realizing it required a fix for 527.
> Use PySide2 from EDM instead of PyPI and Use the latest EDM version (3.0.1)

- chaco/tools/scatter_inspector.py
> Handle index=None in ScatterInspector

- ci/edmtool.py
Currently the cron job testing against master of traits/traitsui/pyface/enable is failing with this:
```
======================================================================
ERROR: chaco.tests.test_array_or_none (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: chaco.tests.test_array_or_none
File "/home/travis/.edm/envs/chaco-test-3.6-null/lib/python3.6/site-packages/pyface/base_toolkit.py", line 73, in <module>
import importlib.metadata as importlib_metadata
ModuleNotFoundError: No module named 'importlib.metadata'
During handling of the above exception, another exception occurred:
File …
```
> Fix cron job not installing additional dependencies

- chaco/contour/cntr.c
- examples/demo/noninteractive.py
part of #483 
This PR removes a few checks for a specific python version and only keeps code specific to python 3+.
Based on this comment: https://github.com/enthought/chaco/blob/4a6683521cce012b5df4830d64f41518798fc817/docs/scipy_tutorial/Scripts/shBrushPython.js#L1
I suspect we Can remove this .js file entirely?
> Remove python version checks

- chaco/api.py
- chaco/cmap_image_plot.py
- chaco/legend.py
- chaco/multi_array_data_source.py
- chaco/plot_containers.py
- chaco/plotscrollbar.py
- chaco/subdivision_mapper.py
- chaco/tools/cursor_tool.py
- chaco/tools/line_segment_tool.py
- chaco/tools/pan_tool2.py
- chaco/tools/range_selection.py
This PR simply removes some commented out code from the code base.
> Remove commented out code

- examples/demo/advanced/cmap_variable_sized_scatter.py
- examples/demo/advanced/data_cube.py
- examples/demo/advanced/scalar_image_function_inspector.py
- examples/demo/advanced/scalar_image_function_inspector_old.py
- examples/demo/basic/cmap_image_aspect_ratio.py
- examples/demo/basic/cmap_image_plot.py
- examples/demo/basic/cmap_image_select.py
- examples/demo/basic/cmap_scatter.py
- examples/demo/basic/contour_plot.py
- examples/demo/basic/discrete_cmap_image_plot.py
- examples/demo/basic/image_inspector.py
- examples/demo/basic/image_lasso.py
- examples/demo/canvas/canvas.py
- examples/demo/cursor_tool_demo.py
- examples/demo/nonlinear_color_mapping.py
- examples/demo/shell/add_tool.py
- examples/demo/shell/contourf.py
- examples/demo/shell/pcolor.py
- examples/demo/vtk/cmap_scatter.py
- examples/demo/vtk/spectrum.py
- examples/tutorials/scipy2008/image.py
- examples/tutorials/scipy2008/traits_image.py
- examples/user_guide/h_plot_container_colorbar.py
fixes #552 
This PR replaces all uses of the jet color map in the examples with viridis.  To do this VS Code replace all was used with
jet->viridis on all files in the examples sub module.  
Some examples may be better suited with a color map different from viridis, but I did not take the time to chose a color map on a per example basis.  I figured at the very least viridis should be better than jet.
If it is needed for particular examples to use a different color map they can be handled specifically
> Replace all jet color map use in examples with viridis

- chaco/tools/better_selecting_zoom.py
The 'control' option is repeated, so I removed the second one.
> Remove redundant 'control' in ZoomTool

- chaco/barplot.py
- chaco/lineplot.py
- chaco/polygon_plot.py
- chaco/toolbar_plot.py
- examples/demo/depth.py
- examples/demo/domain_limits.py
- examples/demo/multi_line_plot.py
- examples/demo/multi_line_plot_demo.py
- examples/demo/status_overlay.py
- examples/demo/vtk_example.py
part of an effort to break #462 down into various smaller PRs
This PR simply pulls changes directly from that PR.  Namely, those changes involving simply updating example file docstrings, or updating comments on trait definitions
> Update various comments and docstrings

- docs/source/user_manual/basic_elements/data_ranges.rst
- docs/source/user_manual/basic_elements/data_sources.rst
- docs/source/user_manual/basic_elements/mappers.rst
- docs/source/user_manual/basic_elements/overlays.rst
- docs/source/user_manual/basic_elements/plot_renderers.rst
part of an effort to break #462 down into various smaller PRs
This PR pulls out the changes to files in `docs/source/user_manual/basic_elements/` from 462.  These changes are effectively style changes / using correct sphinx roles, etc.  The diffs are rather long but content overall the content is effectively unchanged
> Clean up updates for basic_elements docs pages

- chaco/shell/tests/test_tutorial_example.py
- chaco/tests/test_border.py
- chaco/tests/test_cmap_image_plot.py
- chaco/tests/test_colormapped_scatterplot.py
- chaco/tests/test_data_label.py
- chaco/tests/test_plot.py
- chaco/tests/test_scatterplot_renderers.py
- chaco/tests/test_ticks.py
- chaco/tools/tests/test_range_zoom.py
This PR removes unnecessary calls to `unittest.main()` in the test modules.
> Remove unnecessary unittest.main calls in tests

- docs/source/user_manual/quickstart.rst
I inadvertently let these slip through when merging #462 
This PR simply fixes broken image links which resulted from the quickstart rst file being moved inside the `user_manual` folder.
This PR also begs the question of if the outer image folder is still needed?/ why are there some images repeated between the outer and inner images folder (not all the images in quickstart were broken before this PR)
part of #587
> fix broken image links on docs/source/user_manual/quickstart.rst

- chaco/image_plot.py
- chaco/tests/test_image_plot.py
fixes #528 (I think)
With the change made in this PR I no longer see the crash described here: https://github.com/enthought/chaco/issues/528#issuecomment-809297495
This PR simply updates `_calc_zoom_coords` to return what it claims to return:
```
Returns
-------
index_bounds : 4-tuple
The column and row indices (col_min, col_max, row_min, row_max) of
the sub-image to be extracted and drawn into `screen_rect`.
screen_rect : 4-tuple
(x, y, width, height) rectangle describing the pixels bounds where
the image will be rendered in the plot.
```
In this particular case if we have zoomed in so far that the image has either length or width 0, the the screen rect showing it is effectively non-existent, and there is no data to show in it.  
Technically `((0, 0, 0, 0), (0, 0, 0, 0))` isn't really …
> return correct sized tuples of all 0s not None if image plot resized too small

- chaco/scales/tests/test_scales.py
- chaco/scales/tests/test_time_scale_resolution.py
- chaco/tests/test_base_utils.py
- chaco/tests/test_colormapper.py
- chaco/tests/test_datarange_1d.py
- chaco/tests/test_datarange_2d.py
- chaco/tests/test_linearmapper.py
- chaco/tests/test_plotcontainer.py
This PR removes dummy/unnecessary `return` statements in the testsuite.
> Remove dummy return statements in testsuite

- docs/source/user_manual/tutorial_van_der_waal.rst
- examples/demo/advanced/data_cube.py
- examples/demo/advanced/data_stream.py
- examples/demo/advanced/javascript_hover_tools.py
- examples/demo/advanced/spec_waterfall.py
- examples/demo/advanced/spectrum.py
- examples/demo/basic/image_lasso.py
- examples/demo/canvas/axis_tool.py
- examples/demo/canvas/canvas.py
- examples/demo/canvas/cliptest.py
- examples/demo/canvas/data_source_button.py
- examples/demo/canvas/mp_viewport_pan_tool.py
- examples/demo/canvas/mptools.py
- examples/demo/canvas/plot_clone_tool.py
- examples/demo/financial/correlations.py
- examples/demo/noninteractive.py
- examples/demo/updating_plot/updating_plot1.py
- examples/demo/updating_plot/updating_plot2.py
- examples/demo/updating_plot/updating_plot3.py
- examples/demo/updating_plot/updating_plot4.py
- examples/demo/updating_plot/updating_plot5.py
- examples/demo/vtk/spectrum.py
- examples/demo/zoomed_plot/zoom_overlay.py
- examples/tutorials/scipy2008/custom_overlay.py
- examples/tutorials/scipy2008/custom_overlay_dataspace.py
- examples/tutorials/scipy2008/custom_overlay_movetool.py
This PR removes dummy/unnecessary `return` statements from the documentation and examples.
> Remove dummy return statements in docs and examples

- chaco/axis.py
- chaco/barplot.py
- chaco/base_1d_mapper.py
- chaco/base_2d_plot.py
- chaco/base_contour_plot.py
- chaco/base_xy_plot.py
- chaco/chaco_plot_editor.py
- chaco/cmap_image_plot.py
- chaco/color_mapper.py
- chaco/colormapped_scatterplot.py
- chaco/colormapped_selection_overlay.py
- chaco/data_label.py
- chaco/data_range_1d.py
- chaco/data_range_2d.py
- chaco/grid.py
- chaco/grid_mapper.py
- chaco/overlays/databox.py
- chaco/overlays/simple_inspector_overlay.py
- chaco/plot.py
- chaco/plotscrollbar.py
- chaco/scatterplot.py
This PR starts replacing the dynamic uses of on_trait_change with observe equivalents
I am going to arbitrarily stop here to keep this PR shorter to review.  After these changes, there are 18 files left containing `.on_trait_change` which can be addressed in a separate PR.
> Replace dynamic on_trait_change with observe

- chaco/scatter_inspector_overlay.py
- chaco/tools/image_inspector_tool.py
- chaco/tools/range_selection.py
- chaco/tools/range_selection_overlay.py
- chaco/tools/simple_zoom.py
- chaco/tools/tests/test_image_inspector.py
- chaco/tools/tests/test_scatter_inspector.py
- examples/demo/advanced/scalar_image_function_inspector.py
- examples/demo/advanced/scalar_image_function_inspector_old.py
- examples/demo/basic/image_lasso.py
- examples/demo/basic/scatter_inspector.py
- examples/demo/basic/scatter_rect_select.py
- examples/demo/basic/scatter_select.py
- examples/demo/basic/scatter_toggle.py
- examples/demo/chaco_trait_editor.py
- examples/demo/financial/correlations.py
- examples/demo/financial/stock_prices.py
- examples/demo/zoomed_plot/zoom_overlay.py
This PR continues replacing the dynamic uses of on_trait_change with observe equivalents on top of #590
> Replace dynamic on_trait_change with observe part 2

- chaco/plugin/plot_editor.py
fixes #611 
This PR simply imports the needed objects from `traitsui.api` rather than importing the whole thing as tui.
As a side note, this module is based around Workbench which has been deprecated in favor of tasks.  Perhaps we want to rewrite this module? Or deprecate, or remove it... 🤔
> Dont use traitsui.api as tui

- chaco/barplot.py
- chaco/base_1d_plot.py
- chaco/color_bar.py
- chaco/data_label.py
- chaco/data_view.py
- chaco/image_plot.py
- chaco/layers/svg_range_selection_overlay.py
- chaco/lineplot.py
- chaco/multi_line_plot.py
- chaco/polygon_plot.py
- chaco/scatterplot.py
- chaco/segment_plot.py
- chaco/tools/better_selecting_zoom.py
- chaco/tools/cursor_tool.py
- chaco/tools/range_selection_overlay.py
- chaco/tools/toolbars/toolbar_buttons.py
- examples/demo/nonlinear_color_mapping.py
This PR replaces _almost_ all uses of `depends_on` with observe, aside from this:
https://github.com/enthought/chaco/blob/99109d95850864b74ab636f385741b595b671c7c/chaco/base_1d_plot.py#L40
changing this line resulted in he following errors:
<details>
```
======================================================================
FAIL: test_linescatter_1d_set_index_mapper_notifies_index_range (chaco.tests.test_line_scatterplot.LineScatterPlot1DTest)
----------------------------------------------------------------------
File "/Users/aayres/Desktop/chaco/chaco/tests/test_line_scatterplot.py", line 185, in test_linescatter_1d_set_index_mapper_notifies_index_range
self.linescatterplot.index_mapper = LinearMapper(range=new_range)
File …
```
> Replace use of depends_on in Traits Properties with observe

- chaco/legend.py
- docs/source/conf.py
- examples/demo/basic/minard_napoleon.py
This PR simply removes unnecessary coding cookies in files and an end of file marker we missed in an earlier PR.
> Remove miscellaneous/dead code

- chaco/chaco_plot_editor.py
This PR updates the `ChacoPlotEditor` to not hook up the listeners if the trait is `None` or if the trait doesnt exist on the plot object. This was discovered when running the examples https://github.com/enthought/chaco/blob/fdd858aa6dbc76addb50d011fb81e879ce8e0355/examples/demo/basic/traits_editor.py and https://github.com/enthought/chaco/blob/fdd858aa6dbc76addb50d011fb81e879ce8e0355/examples/demo/advanced/data_stream.py
> Dont hook up listeners in ChacoPlotEditor if the trait is None

- chaco/plotscrollbar.py
- chaco/tests/test_colormapper.py
- examples/demo/nonlinear_color_mapping.py
fixes #612 
This PR removes unnecessary print statements and dead code/tests
> Remove unnecessary print statements

- docs/source/conf.py
If the package is installed in a non-editable way, the `_version` file won't exist where we expect it to. This PR updates the sphinx configuration to get the version information from the package directly if the file doesn't exist.
> Import version from installed package if the file doesnt exist

- chaco/plot_component.py
- docs/source/index.rst
- docs/source/user_manual/basic_elements/data_sources.rst
- docs/source/user_manual/basic_elements/overlays.rst
- docs/source/user_manual/basic_elements/plot_renderers.rst
- docs/source/user_manual/basic_elements/tools.rst
- docs/source/user_manual/chaco_tutorial.rst
- docs/source/user_manual/containers.rst
- docs/source/user_manual/faq.rst
- docs/source/user_manual/plot_types.rst
- docs/source/user_manual/quickstart.rst
- docs/source/user_manual/tutorial_hyetograph.rst
- docs/source/user_manual/tutorial_van_der_waal.rst
This PR makes a number of miscennaleous documenation fixes and changes. These were made when reviewing the entire documentation. Most of the changes are style changes in the example code included, some are spelling corrections and some fix rendering issues with sphinx.
> Miscellaneous documentation fixes/changes

- docs/source/user_manual/index.rst
This PR simply removes the annotated examples links from the user guide.  They are already linked from the home page of the documentation, and they simply cloud the user manual TOC.
> Remove annotated examples from the usermanual

- chaco/plugin/workbench_session.py
- chaco/shell/commands.py
- chaco/shell/plot_window.py
- chaco/shell/session.py
- chaco/tests/test_speedups.py
closes #609 
This PR simply updates the uses of the `property` function to use the `@property` decorator.  Also, users of the property now access the property without calling the `get____` or `set___` methods.
> Use @property decorator instead of property function

- chaco/abstract_colormap.py
- chaco/base.py
- chaco/base_candle_plot.py
- chaco/base_contour_plot.py
- chaco/chaco_plot_editor.py
- chaco/chaco_traits.py
- chaco/data_frame_plot_data.py
- chaco/function_data_source.py
- chaco/function_image_data.py
- chaco/jitterplot.py
- chaco/shell/preferences.py
- chaco/shell/session.py
- chaco/tools/base_zoom_tool.py
- chaco/tools/cursor_tool.py
- chaco/tools/pan_tool2.py
- chaco/tools/rect_zoom.py
- chaco/tools/scatter_inspector.py
- chaco/tools/simple_zoom.py
- chaco/tools/tool_history_mixin.py
- chaco/tools/toolbars/plot_toolbar.py
closes #615 
This PR simply audits the code base for public trait definitions that use # instead of #: and replaces them as needed.  Note some of the modules changed here may soon be deprecated.
> Use #: instead of # when needed

- chaco/tests/test_plot.py
This PR attempts to fix the CI failure observed here: https://github.com/enthought/chaco/pull/633#issuecomment-818831955 and https://github.com/enthought/chaco/pull/649#issuecomment-818799658
TBH I do not understand the error entirely yet. It doesn't make sense to me that '_QtWindow' object has no attribute 'handler' as it is explicitly defined in the `__init__` method of '_QtWindow' .  Further I don't get how that would be a windows specific problem....
_Nonetheless_, the error is occurring in a `leaveEvent` method.  This PR is really a hunch (I don't have a windows machine so I am opening the PR to see if it actually fixes the problem).  I changed the coordinates of the drag in the test to hopefully avoid any sort of `leaveEvent` occurring. Leaving the window is actually not the …
> fix windows/pyqt test_dont_crash_on_click failure

- chaco/axis.py
- chaco/axis_view.py
- chaco/chaco_plot_editor.py
- chaco/colormapped_scatterplot.py
- chaco/grid.py
- chaco/lineplot.py
- chaco/multi_line_plot.py
- chaco/plugin/plot_editor.py
- chaco/scatterplot.py
- docs/source/user_manual/annotated_examples.rst
- docs/source/user_manual/chaco_tutorial.rst
- docs/source/user_manual/common_patterns.rst
- docs/source/user_manual/faq.rst
- docs/source/user_manual/how_do_i.rst
- docs/source/user_manual/modules_and_classes.rst
- docs/source/user_manual/tutorial_van_der_waal.rst
- examples/demo/chaco_trait_editor.py
This PR does a repo-wide search and replace for `"Traits UI"` with `"TraitsUI"`. After the automated search and replace, the changes were checked and modified.
> Its TraitsUI, not Traits UI

- chaco/barplot.py
- chaco/color_bar.py
- examples/demo/zoomed_plot/grid_plot_factory.py
- examples/demo/zoomed_plot/zoom_plot.py
This PR removes unnecessary uses of `use_draw_order` in the code - which is by default `True` - and redefinition of the `use_draw_order` trait on a `PlotComponent` subclass and a commented out piece of code.
Note that I tested the `zoomed_plot` and it still works as expected. You need to do `python -m zoomed_plot.zoom_plot` if you want to run the example (which I think needs to be documented somewhere).
Related to #659
> Remove unnecessary uses of "use_draw_order"

- chaco/tests/test_plot.py
It seems #663 was actually unsuccessful (see #665, #633)
This PR simply skips the test entirely for now to avoid CI headaches on future PRs
> skip test_dont_crash_on_click on windows/pyqt

- chaco/axis.py
- chaco/base_plot_container.py
- chaco/grid.py
- chaco/plot_component.py
fixes #659 
This PR simply removes all the uses / definitions of the `use_draw_order` trait. A similar PR is coming shortly in enable.
> Remove all uses/definitions of use_draw_order

- chaco/multi_line_plot.py
- examples/demo/advanced/javascript_hover_tools.py
- `multi_line_plot.py`
- `multi_line_plot_demo.py`
- `javascript_hover_tools.py`
The first two were failing earlier because of a bad listener hookup. The latter was failing because of the use of non-existent methods.
> Fix a couple of demos

- examples/demo/advanced/javascript_hover_tools.py
- examples/demo/basic/grid_container.py
- examples/demo/basic/grid_container_aspect_ratio.py
- examples/demo/bigdata.py
- examples/demo/canvas/data_source_button.py
- examples/demo/data_labels.py
- examples/demo/edit_line.py
- examples/demo/financial/correlations.py
- examples/demo/multiaxis.py
- examples/demo/multiaxis_using_Plot.py
- examples/demo/noninteractive.py
- examples/demo/scales_test.py
- examples/demo/simple_line.py
- examples/demo/stacked_axis.py
- examples/demo/tornado.py
- examples/demo/vertical_plot.py
- examples/user_guide/grid_plot_container.py
Some of the examples import `cbrewer` from `chaco.api` as `COLOR_PALETTE` from `chaco.example_support`. I am not sure `chaco.example_support` should be a public module and I don't think we should be promoting this usage. This PR replaces all instances of `from chaco.example_support import COLOR_PALETTE` with `from chaco.api import cbrewer as COLOR_PALETTE`.
> Import color palette from chaco.api directly

- chaco/api.py
- chaco/chaco_traits.py
This PR removes backwards compatibility imports from `enable` in `chaco.api` and `chaco.chaco_traits` .
fixes #638 and #628
> Remove backwards compatibily imports from enable

- chaco/color_mapper.py
part of #580
This PR removes the deprecated `ColorMapper._map` method.
> Remove deprecated "ColorMapper._map" method

- chaco/colormapped_scatterplot.py
- chaco/tests/test_colormapped_scatterplot.py
fixes #425 
This can close issue #232 as well after https://github.com/enthought/enable/pull/782 is merged
In enable:
https://github.com/enthought/enable/blob/master/enable/markers.py
some markers have a defined `kiva_marker` while others simply define an `_add_to_path` method detailing how to draw the marker manually. If the marker has `kiva_marker` we can use `draw_marker_at_points`, but if it doesn't we need to fall back to manually drawing the path via the `_add_to_path` method and calling `draw_path_at_points`.
> Use draw_marker_at_points if possible otherwise use draw_path_at_points in ColormappedScatterPlot

- examples/demo/advanced/scalar_image_function_inspector.py
closes #607 
This PR removes `optparse` in https://github.com/enthought/chaco/blob/ef7227706642f7d26042717ad9b60648d7572068/examples/demo/advanced/scalar_image_function_inspector.py and also fixes the following error:
```
$ python examples/demo/advanced/scalar_image_function_inspector.py -n 50
2021-04-12 16:29:40.435 Python[68324:22123757] ApplePersistenceIgnoreState: Existing state will not be touched. New state will be written to (null)
Exception occurred in traits notification handler for object: <__main__.PlotUI object at 0x7fee44635200>, trait: num_levels, old value: 15, new value: 50
File "/Users/aayres/.edm/envs/chaco-test-3.6-pyqt5/lib/python3.6/site-packages/traits/trait_notifiers.py", line 342, in __call__
self.handler(*args)
File …
```
> Remove optparse from example

- ci/edmtool.py
- ci/requirements.txt
- setup.py
- tox.ini
- travis-ci-requirements.txt
This PR makes a number of changes to the ci module and setup script
- removes use of `use_2to3` in setup script
- fixes flake8 errors and failures in setup script
- fixes flake8 errors in ci module
- moves `coverage` from requirements file to edmtool so it can be installed via edm instead of pypi
- removes unused `travis-ci-requirements.txt`
- update tox config file to remove fixed up files from flake8 ignore list
> Cleanup ci module and setup

- examples/demo/advanced/data_cube.py
- examples/demo/aspect_ratio.py
- examples/demo/basic/bar_plot_stacked.py
- examples/demo/depth.py
- examples/demo/domain_limits.py
- examples/demo/multi_line_plot.py
- examples/demo/status_overlay.py
- examples/demo/toolbar_plot.py
- examples/demo/xray_plot.py
Part of #658 
This PR replaces the `__init__` method in many examples with the `_plot_default` approach.  This is not all the examples, but the remaining can be done in a follow up PR.
> Use a plot default method instead of overriding the init method in examples

- chaco/tests/_tools.py
- chaco/tests/test_2d_case.py
This PR replaces the use of the custom `assert_raises` context manager with the `unittest.TestCase.assertRaises` and removes the custom `assert_raises` context manager.
> Replace custom "assert_raises" with "unittest.TestCase.assertRaises"

- chaco/tests/test_colormapped_scatterplot.py
This was fixed in #672 but I originally thought it needed https://github.com/enthought/enable/pull/782 in a released version of enable before the test could be unskipped.  
This is actually not the case (although the fix n enable is still needed, the changes in 672 avoid the problem ever getting reached.
This PR simply un skips the test that is now passing
> Unskip no longer failing test

- examples/demo/advanced/spec_waterfall.py
- examples/demo/advanced/spectrum.py
- examples/demo/basic/image_from_file.py
- examples/demo/canvas/cliptest.py
- examples/demo/financial/correlations.py
- examples/demo/updating_plot/updating_plot2.py
- examples/demo/updating_plot/updating_plot3.py
- examples/demo/updating_plot/updating_plot4.py
- examples/demo/updating_plot/updating_plot5.py
- examples/user_guide/h_plot_container.py
- examples/user_guide/h_plot_container_add_multiple_times.py
- examples/user_guide/h_plot_container_colorbar.py
closes #658 
There are still some examples which define an `__init__` method.  However they either are ding something where they likely need to keep it or they belong to `examples/tutorials/scipy2008/` in which I didn't touch them.
This PR also fixes many of these examples which previously had been broken (trivial changes eg defining `_create_component` not `_create_window`, or using ints instead of floats).
> Use a plot default method instead of overriding the init method in examples part 2

- docs/source/index.rst
part of #587 
The FAQ page does not have very useful information, and it makes more sense to link to the How do I page from the home page of the docs (although it is still a WIP)
> Link to "how do i", not "faq", from home page

- chaco/tools/regression_lasso.py
Instead of `LassoOverlay._draw_component`, we use `super()._draw_component` instead. `LassoOverlay` is what `RegressionOverlay` inherits from.
> Use "super" instead of calling method on class explicitly

- examples/demo/financial/stock_prices.py
fixes #719 
During the on_trait_change to observe changes, we defined `plot_range_event = event.new`, but missed a place where it needed to be used in place of event.
With this simple change I no longer see the error and zooming appears to work as expected.
> use plot_range_event (aka event.new) not just event in stock_prices

- ci/edmtool.py
ref: https://github.com/enthought/chaco/issues/553#issuecomment-834737981
This PR follows the lead of other ETS packages by allowing developers to pass a `--editable` flag to the `install` ci command to install the package in editable mode as a convenience.
> add editable option to ci install command

- chaco/plot_factory.py
closes #617 
This PR simply replaces having a mutable default `data=[]` with `data=None` and immediately sets data to a new empty list if data is None.
> replace [] default for data with None

- chaco/api.py
- chaco/polar_mapper.py
closes #629 
This PR simply re-exports the 2 classes from the api module.
It also pulls a comment about `PolarMapper` currently just being LinearMapper into the docstring so it appears on api docs.  Eventually we will want to update it, see #47.  In the meanwhile it is fine to like in the api as long as this is documented.
(Actually looking at it, it looks like some changes have been made to LinearMapper that weren't copied over... I may go ahead and pull those directly so that the PolarMapper really does just match the LinearMapper like it says).
EDIT: done. The PolarMapper is now the current LinearMapper rather than an old version of the LinearMapper.
> re-export PolarLineRenderer and PolarMapper from chaco.api

- chaco/array_data_source.py
- chaco/tests/test_arraydatasource.py
closes #245 
I updated the method to handle the case when _data is None to avoid an error.
I also rewrote the assertions of the test.  I couldn't make sense of the old ones given the current code
> fix broken test and handle case when _data is None in ArrayDataSource.get_data_mask()

- chaco/tests/test_cmap_image_plot.py
- chaco/tools/tests/test_range_zoom.py
- ci/edmtool.py
`mock` is now in the standard library since python 3.3. This PR updates the codebase to use mock via unittest.
Python 2 is end of life and we plan to drop support for 5.0.0 release
> use mock through unittest

- chaco/layers/status_layer.py
- chaco/layers/svg_range_selection_overlay.py
Part of #736 (maybe this is enough to close the issue?  We may want to remove all use of _draw_component, even uses that won't break)
These 2 calls actually were calling `Component._draw_component` living in `enable` which currently is a no-op:
https://github.com/enthought/enable/blob/21c299e1229d74e9db701487a613934e332a7225/enable/component.py#L344-L350
There are other uses of `_draw_component` across chaco that can be removed, but they will not cause a break if `_draw_component` is removed in `enable` (ref https://github.com/enthought/enable/pull/814), because the method gets overwritten in chaco.
> remove calls to Component._draw_component

- examples/demo/advanced/cmap_variable_sized_scatter.py
- examples/demo/basic/contour_cmap_plot.py
- examples/demo/basic/contour_plot.py
- examples/demo/basic/image_plot.py
- examples/demo/basic/line_drawing.py
- examples/demo/basic/scatter.py
- examples/demo/basic/scatter_1d.py
- examples/demo/basic/scatter_alpha.py
- examples/demo/basic/scatter_custom_marker.py
- examples/demo/basic/scatter_rect_select.py
- examples/demo/basic/scatter_select.py
- examples/demo/basic/scatter_toggle.py
- examples/demo/basic/scatter_variable_size.py
- examples/demo/basic/segment_plot.py
ref: https://github.com/enthought/enable/pull/816#pullrequestreview-661608507
This PR removes uses of the soon to be removed, deprecated `bg_color` trait from enable.  For consistency it renames all uses of `bg_color` in the codebase with `bgcolor` (even just temp variables), in order to keep consistent.  Note, all changes occur in example code
> Replace bg_color with bgcolor

- chaco/axis.py
- chaco/legend.py
- examples/demo/advanced/scalar_image_function_inspector.py
closes #624 
Note there are still a few examples using `_anytrait_changed` methods that can be addressed in a different PR.  I ended up not using metadata in the `legend.py` and just went with the straight forward conversion to observe.  We can come back to this if we want to be a little more clever later.
> Replace some _anytrait_changed methods

- chaco/api.py
- chaco/scaly_plot.py
`ScalyPlot` was removed in #667, however it is still used / needed.
It was independent of any other aspect of `chaco.shell` and is brought back here to simply sit in `chaco.scaly_plot.py`.
~NOTE: we are planning some internal reorg (see #738), so this module may be moved in the future.~
It should be imported for the api module (I will add it to the api in this PR)
> Revive ScalyPlot

- MANIFEST.in
following the lead of https://github.com/enthought/enable/pull/836
This was missed in PR #730
> Add pyproject.toml to MANIFEST.in

- chaco/__init__.py
[targeting maint/5.0]
This PR updates `__requires__` to be more specific. 
We use `Property(observe=...)` and so depend on traits >= 6.2.  Also recent changes are such that we require enable 5.2 (only rc currently available).  Also enable 5.2 (and actually I think 5.1) require pyface >=7.2 as it uses `pyface.undo`.  So, chaco implicitly requires pyface >= 7.2
TBH I am not exactly sure on what traitsui is necessary (we didnt specify for enable either)
This PR will eventually need to be backported into master along with the recent changelog updates
> Update requirements to be more specific

- setup.py
The merge commit from this PR will be tagged as the release candidate
> Chaco Release Candidate 5.0.0

- setup.py
This PR simply flips `IS_RELEASED` back to False following the 5.0.0 release candidate, for continued development in advance of the full 5.0.0 release
> flip IS_RELEASED back to false for continued development

- chaco/plot_containers.py
This PR refactors the chaco `OverlayPlotContainer` to inherit from the enable `OverlayContainer`. This PR makes small changes in each commit that slowly move `OverlayPlotContainer` away from the chaco `BasePlotContainer` by redefining the traits on the latter on the former. Finally, we update the inheritance and remove redundant methods on the `OverlayPlotContainer`.
Note that we would like this PR to be backported to the `maint/5.0` branch so that it can be included in the final `maint/5.0` release.
> Refactor chaco OverlayPlotContainer to inherit from enable OverlayContainer

- .github/workflows/test-with-edm.yml
- chaco/plot_containers.py
- ci/edmtool.py
This PR refactors the `HPlotContainer` and `VPlotContainer` classes in enable to inherit from the enable `HStackedContainer` and `VStackedContainer` respectively. This removes duplicate code between chaco and enable. In the end, in our opinion, the `*PlotContainer` classes in chaco are more-readable than they were before.
Note that this PR was written with enable main branch in mind - but it should work with the current release of `enable` as well. This PR is what will introduce the dependency on `enable >= 5.2` on the upcoming `chaco` major release.
This PR can be reviewed one commit at a time as we have taken great care to keep the commits self-contained. Each commit makes only one type of change, which we hope will make the review process simpler.
This is the last big PR extracted from …
> Make chaco v/h plot containers inherit from enable v/h stacked containers

- .github/workflows/test-with-edm.yml
- chaco/plot_containers.py
- ci/edmtool.py
This PR backports #757 , #758 and #764 into the `maint/5.0` branch in preparation for the 5.0 release of chaco.
> Backport Plot Containers refactor to 5.0 maintenance branch

- chaco/axis.py
- chaco/base_xy_plot.py
- chaco/grid.py
- chaco/overlays/lasso_overlay.py
- chaco/plots/colormapped_scatterplot.py
- chaco/plots/polar_line_renderer.py
- chaco/tools/regression_lasso.py
targeting `maint/5.0`
This PR backports the recent PR #743, which removed unnecessary definitions and uses of the `_draw_component` method,  to the `maint/5.0` branch.
> Backport Remove all definitions / uses of _draw_component (#743)

- chaco/axis.py
This got broken in #743 
`component` was always None in this case (hence the removed `if component is not None:`.  I had just missed this before.
> Fix _draw_overlay in chaco.axis

- chaco/axis.py
This had been broken in PR #743 and was recently fixed on the maint/5.0 branch.  This PR simply pulls that fix back up into master
> Backport fix of chaco.axis 

- CHANGES.txt
- pyproject.toml
This PR backports the recent fix to `pyproject.toml` to the `maint/5.0` branch and updates the changelog.
> Backport pyproject toml fix 

- chaco/plots/tests/test_image_plot.py
- chaco/tests/test_plot.py
targeting `stop-testing-pyqt4`.  This PR sits on top of #782 and removes unneeded (unneeded once pyqt is no longer tested on CI) checks / code blocks for pyqt4.
> Remove is_qt4 checks

- chaco/base_2d_plot.py
- chaco/base_xy_plot.py
- chaco/plot.py
- chaco/selectable_legend.py
- chaco/tests/test_array_or_none.py
- chaco/tools/image_inspector_tool.py
- chaco/tools/regression_lasso.py
This PR addresses deprecation warnings raised in chaco because of the recent moves in chaco i.e. `chaco.plots` and `chaco.overlays`. Note that this PR needs to be backported to the `maint/5.0` branch and included in the 5.0 release.
> Address deprecation warnings because of moved modules in chaco

- chaco/__init__.py
Now that enable 5.2.0 has been uploaded to pypi, we can explicitly add the requirement. 
This PR should be pulled back into master as well
> Explicitly require enable 5.2.0 which is now on PyPI

- setup.py
This PR simply bumps the version number in setup.py for continued development.
> Bump version and set IS_RELEASED to False for development of 5.0.1

- docs/source/user_manual/basic_elements/tools.rst
- docs/source/user_manual/tutorial_hyetograph.rst
- docs/source/user_manual/tutorial_van_der_waal.rst
Ref: #792 
This PR fixes a couple other links to examples in the documentation.  Note these changes _were_ included in the gh-pages PR
> Fix a couple more links in documentation

- docs/source/annotated_examples.rst
- docs/source/user_manual/basic_elements/tools.rst
Follow up to #793 
These changes also went into #792.
Only some of the examples included in the documentation were moved into the package.  I went through and tested the links on the annotated examples page and now they finally all work as expected.  Additionally the tools page link pointed out on 792/ 793 is fixed here.
> fix more broken links

- .github/workflows/test-with-edm.yml
- ci/edmtool.py
This PR backports PR #795 to the `maint/5.0` branch - updating CI to use enable from EDM instead of installing it from git/github source.
> Backport #795 - Use enable from edm instead of git/github source

- chaco/plot_containers.py
These methods were pulled up into the `StackedContainer` base class in enable in PR https://github.com/enthought/enable/pull/841
Note that PR was merged into enable master and we test against enable maint/5.2.  Once https://github.com/enthought/enable/pull/845 is merged we can go ahead with this PR.
Note this PR should not block the release.  If it does get merged in time in can be backported into `maint/5.0`.
> Remove unneeded __getstate__ methods

- chaco/plot_graphics_context.py
part of #785 
As mentioned in the issue, we can resolve many test suite errors with celiagg by enforcing these be ints.  Note that scale itself I think can be a float (e.g. the `scale_ctm` method expects floats as arguments), however, `size_or_ary` gets used as a `_width` and `_height` and is assumed to contain integers. 
~Note, with this change I now see 2 failures in the test suite:~ EDIT: I only see the one error mentioned on the issue:
```
======================================================================
FAIL: test_draw_border_simple (chaco.tests.test_border.DrawBorderTestCase)
Borders should have the correct height and width.
----------------------------------------------------------------------
File …
```
> Specify size_or_ary contains ints

- .github/workflows/ets-from-source.yml
- .github/workflows/test-with-edm.yml
This PR adds a cron job on GH Actions (ultimately we would like to drop travis).
> Add an ets-from-source cron job on GH Actions

- chaco/base_xy_plot.py
- chaco/examples/demo/basic/hittest_tool.py
- chaco/plots/barplot.py
- chaco/plots/errorbar_plot.py
- chaco/plots/lineplot.py
- chaco/plots/scatterplot.py
- chaco/plots/segment_plot.py
- chaco/tests/test_plot.py
fixes #272 
This PR pulls out the changes specific to `BaseXYPlot` and its subclasses from #726
> Fix BaseXYPlot map_screen

- chaco/linear_mapper.py
- chaco/plots/lineplot.py
- chaco/tools/cursor_tool.py
- chaco/tools/tests/test_cursor_tool.py
fixes #289 
This PR pulls the content specific to #289 out from PR #726
> Fix CursorTool issue with LogMapper

- chaco/tools/data_label_tool.py
- chaco/tools/tests/test_data_label_tool.py
This PR adds a regression test and a fix for the specific error reported on #550.
550 is a bit broader in scope though and would also include #802 (and probably more) to be closed.
Note the changes here were pulled from #726 in an effort to make smaller more reviewable PRs.  However, there is some interconnectedness between these PRs.  This PR should not be merged first, as it will break things without the change in #802
As the issue mentions, currently the `DataLabelTool` is forced to assume the `BasaeXYPlot` way or the `Base2DPlot` way. 
"This difference forces objects that interact with `AbstractPlotRenderers` to make an assumption about the behavior of the `map_screen` method. For example, the `DataLabelTool` assumes the map_screen return shape matches that of `BaseXYPlot` for a …
> Add regression test / fix for DataLabelTool

- chaco/base_1d_plot.py
- chaco/base_2d_plot.py
- chaco/data_view.py
- chaco/plots/jitterplot.py
- chaco/plots/polar_line_renderer.py
- examples/demo/advanced/spec_waterfall.py
This pulls some additional changes out of #726.
This is to keep the return type for the method consistent
> Make map_screen return an empty array not empty list in empty input case

- chaco/examples/demo/basic/hittest_tool.py
This example became broken by the recent changes to map_screen.
This change was pulled from #726 
Note there are some other examples which did not get pulled into `chaco/examples` that could be fixed as well.  I did not do that as I could not recall if they were planned to be deleted entirely.  See #726 changes to `examples/tutorials/...` 
I am happy to make those changes on this PR if need be.
> fix hittest_tool.py example use of map_screen

- chaco/plots/tests/test_image_plot.py
This PR pulls the test added in #726 for testing the map_screen method on ImagePlot.
> add test for ImagePlot map_screen

- chaco/plots/horizon_plot.py
- chaco/polar_mapper.py
This PR contains the last bit of changes which need to be pulled from #726
It simply updates `BandedMapper` / `PolarMapper` to follow the lead of their base class `LinearMapper`.
After all these are merged, I will do a final sweep of the code base to see that nothing else needs to be updated with the recent return type changes (plan is to do code base searches for `map_screen`, etc. / to go through examples and ensure they all work as expected.  Test suite will pass as it has passed on every PR, but just to be sure we didn't miss / break anything in the process not covered by the test suite).
> Enforce data array is array in BandedMapper / PolarMapper

- .github/workflows/ets-from-source.yml
This PR sets up the slack notifications for the cron jobs. I manually triggered the cron jobs on this branch to ensure that the slack notifications are fired as expected. Ref https://github.com/enthought/chaco/actions/runs/1027318233
One more step towards https://github.com/enthought/ets/issues/65
> Setup slack notification for cron jobs

- .readthedocs.yaml
- chaco/__init__.py
This PR adds a basic configuration file for Read the Docs. These changes are based on enthought/traits#1478. This is one more step towards enthought/ets#69.
This PR also add a docs extras_require when installing traitsui to make it easy to build the sphinx docs.
> Add a RtD config file

- chaco/data_view.py
- chaco/tests/test_data_view.py
closes #564
Currently, with manual testing this seems to work how I want it to but I am not sure the current solution is worth the added complexity. 
If we're going to add complexity to the code I think it might be better to try and get a more "perfect" approach that sets padding directly based off of the axis title extent.  Hence the WIP title as I am still thinking about alternate solutions.
> Change default padding based on axis titles

- README.rst
- ci/edmtool.py
- docs/source/annotated_examples.rst
- docs/source/user_manual/chaco_tutorial.rst
- docs/source/user_manual/tutorial_hyetograph.rst
- docs/source/user_manual/tutorial_van_der_waal.rst
This PR replaces the use of ``master`` in the repo with ``main`` as the default branch has been renamed.
>  Default branch has been renamed from "master" to "main"

- docs/source/annotated_examples.rst
- docs/source/conf.py
- docs/source/user_manual/chaco_tutorial.rst
- docs/source/user_manual/tutorial_hyetograph.rst
- docs/source/user_manual/tutorial_van_der_waal.rst
At the moment, the documentation links to examples on the `main`/default branch. This isn't right because the examples might change in between releases, potentially confusing users who are referring to the documentation. This PR fixes that problem by making the documentation use version-specific links i.e. for the 5.0.0 release, the `5.0.0` tag will be used instead of the `main` branch.
I tested this locally by checking the links generated in the built docs - the examples links will be broken as expected as the dev version has no corresponding tag on GitHub. I then hardcoded the version in the sphinx configuration to `5.0.0` and the links worked as expected, pointing to the `5.0.0` tree instead of `main`.
Note that this commit also creates the new `github-demo` external link using the …
>  Don't link to examples on the main branch in documentation

- examples/demo/advanced/spectrum.py
The spectrum demo had two small issues (`linspace` complains about being fed floats and `scipy.fft` is now apparently a module).﻿
> FIX: Make spectrum demo runnable

- chaco/data_range_1d.py
- chaco/data_range_2d.py
- chaco/tests/test_datarange_1d.py
- chaco/tests/test_datarange_2d.py
Fixes #834 
- suppresses "invalid value" warnings in numpy when computing range masks in the `BaseDataRange` API implementations
- doesn't change behavior, apart from warning suppression
The default behavior of float comparison with `nan`s is consistent with the `mask_data` abstract specification (being "inside the range" implies being finite), so it should be fine to confidently use it without warnings.
By the way, all uses of `mask_data` in the Chaco codebase outside of the classes themselves are already paired with a `& nan_mask`. I'm not sure if that's redundant, but it makes me confident that exluding `nan`s from masks is expected everywhere.
---
¹ ~a curious finding: apparently transposing an array defuses the warning in the first place~
<details>
```python
>>> import numpy as np …
```
> FIX: suppress invalid data warnings for handling NaNs in DataRange classes

- chaco/__init__.py
- ci/edmtool.py
- docs/source/conf.py
This PR does the following: 
- Use the `sphinx_copybutton` extension when building the Sphinx documentation
- Make `sphinx-copybutton` a `docs` extra for the `chaco` package
- Add a `pypi_dependencies` section to the `ci/edmtool.py` utility and add `sphinx-copybutton` as a PyPI dependency for the moment.
Ref https://sphinx-copybutton.readthedocs.io/en/latest/
> Use the "sphinx-copybutton" extension in documentation

- .github/workflows/release-to-pypi.yml
This will need appropriate secrets added.
> Add action to publish to PyPI

- chaco/axis.py
- chaco/ticks.py
This PR includes a defensive programming "fix" to #824 to prevent plot crashing.  The real fix would be to track down where the bad inputs are coming from.  However, regardless I think it makes sense for auto_ticks to be more robust to bad inputs as was discussed on the issue.
Also, in the same downstream project, when an application is resized to be very small and an inspector pane visibility is toggled, the plot some how ends up in a situation where `datalow > datahigh` in `chaco.axis.py` and we are hitting the `RunTimeError`.  I believe it makes sense to handle this case the same that we do for where `datalow == datahigh` (namely there is no plot we could show so we have no ticks).
I am unable to cause the downstream project's plots to crash when working off of this branch.
> Prevent axis related plot crash when plot is resized too small

- .github/workflows/test-with-edm-3.8.yml
- chaco/plot_containers.py
- ci/edmtool.py
- pyproject.toml
This adds a parallel set of tests for Python 3.8 rather than trying to adapt the current set of tests.  Also updates edmtool to allow Python 3.8 and PySide6, and pyproject.toml to allow for known issue with setuptools.
Needed to make one change to code due to newer version of NumPy being picked up.
No requirement that they pass for PRs to be mergeable yet, but will likely add that once this PR is approved.
> Add Python 3.8 tests

- chaco/multi_array_data_source.py
- chaco/tools/lasso_selection.py
This PR replaces `np.bool` with the built in `bool`, was originally #847 but branch name was problematic.
> Use `bool` instead of deprecated `np.bool`

- chaco/plots/image_plot.py
- chaco/plots/tests/test_image_plot.py
- chaco/tools/pan_tool.py
- chaco/tools/tests/test_data_label_tool.py
After this all Python 3.8 tests should pass with no warnings or errors.
This fixes #854 and fixes #855
> Fix Test Warnings on Python 3.8

- .github/workflows/ets-from-source.yml
- .github/workflows/test-with-edm-3.8.yml
- .github/workflows/test-with-edm.yml
- chaco/axis.py
- chaco/multi_array_data_source.py
- chaco/plot_containers.py
- chaco/plots/image_plot.py
- chaco/plots/tests/test_image_plot.py
- chaco/ticks.py
- chaco/tools/lasso_selection.py
- chaco/tools/pan_tool.py
- chaco/tools/tests/test_data_label_tool.py
- ci/edmtool.py
- pyproject.toml
> Backport fixes for 5.1.1 release

- CHANGES.txt
- setup.py
This is a small bugfix release centered around Python 3.8+ support.
> Release 5.1.1

- examples/demo/advanced/spec_waterfall.py
A float is inputed to linspace as sample number which causes error, this pr fixes it
closes issue #869 
Though a new error happens:
(py311) cyliu@aus552cyliu chaco % python3.11 examples/demo/advanced/spec_waterfall.py         
traitsui.__version__ 8.0.0.dev0
pyface.__version__ 7.4.4
2023-03-31 10:35:54.804 Python[3049:51857] ApplePersistenceIgnoreState: Existing state will not be touched. New state will be written to /var/folders/2z/kylzj9s92y71cxscmljmpqrh0000gt/T/org.python.python.savedState
/Users/cyliu/Documents/3.11_test/chaco/examples/demo/advanced/spec_waterfall.py:178: DeprecationWarning: The binary mode of fromstring is deprecated, as it behaves surprisingly on unicode inputs. Use frombuffer instead
audio_data = fromstring(stream.read(NUM_SAMPLES), dtype=short)
Traceback (most …
> MAINT: fix float input for number of samples

- examples/demo/advanced/javascript_hover_tools.py
replacing encodestring (no longer usable) with encodebytes
closes issue #868
> MAINT: fix encode string

- examples/user_guide/plot_types/create_plot_snapshots.py
The load_boston dataset is deprecated, replacing with the diabetes dataset (seems to the the only usable dataset in sklearn.dataset, iris and california housing dataset is not compatible with the code).
**However, there are two more errors arised after the fix that I found the fixes but want to discuss:**
**After correcting the dataset, an error will happen in get_image_from_file() since this function tries to read an image in the demo/basic/capitol.jpg, but the folder doesn't seem to exist anymore, removing this function can fix this problem.**
**Then, another error will happend in chaco.chaco.plots.polar_line_renderer, in function _draw_plot(). Function will try to call _render on gc (line 136), which is a parameter not exists. Removing this line can solve the problem** (this also …
> MAINT: replace deprecated boston dataset with diabetes

- chaco/plots/polar_line_renderer.py
Found that the gc (GraphicsContext) is referenced before construction in the line 136. This has caused the test chaco/chaco/examples/demo/simple_polar.py to fail.
The solution is to find the gc in the context. A gc context is actually conveniently included in the *args, thus retrieving that gc as GraphicContext to solve the problem. closes #875
> fix gc undeclare

- examples/demo/world_map.py
The chaco/examples/demo/world_map demo example is broken due to the original image link in the example has expired. This PR replaces it with a new example.
> fix world_map demo with new link

- chaco/__init__.py
- examples/demo/zoomed_plot/zoom_plot.py
- examples/user_guide/plot_types/create_plot_snapshots.py
After the capitol.jpg moved, chaco/examples/user_guide/plot_types/create_plot_snapshots is broken, use importlib.resources to find the image for loading to fix this
> Fix capitol image

- chaco/plots/barplot.py
- chaco/plots/tests/test_barplot.py
Also somewhat better handling of cropping rectangles that are offscreen for common cases.
Includes basic tests.
Fixes #845
> Handle `nan` in barplots.

- .github/workflows/ets-from-source.yml
This should fix the test failures being seen in the bleeding-edge test runs.
Passing workflow run: https://github.com/enthought/chaco/actions/runs/4956225648/jobs/8866423362
> Use Python 3.8 for tests from source

- chaco/overlays/legend.py
- chaco/tools/legend_highlighter.py
This fixes `Legend.get_label_at()` to return the entire legend label region, including icon, which then allows `LegendHightlighter` to use the actual mouse position to perform it's hit detection.
Fixes #825
> Fix `LegendHiglighter` hit detection

- chaco/data_range_1d.py
- chaco/tests/test_datarange_1d.py
The `updated` event on a `DataRange1D` was not being fired when the last data source was removed.  This fixes that.
Fixes #821
> Fire Range `updated` event when data sources are set to empty

- chaco/api.py
- chaco/tests/test_api.py
- docs/source/user_manual/chaco_tutorial.rst
Add it back to chaco.api but with a deprecation warning.
Fixes #771
> Fix imports of `marker_trait`
