enthought/chaco

- chaco/data_label.py
- chaco/tests/test_data_label.py
> BUG: Fix undefined variable in DataLabel when arrow_visible is False.

- chaco/line_scatterplot_1d.py
- chaco/scatterplot_1d.py
- chaco/tests/line_scatterplot_test_case.py
- chaco/tests/scatterplot_1d_test_case.py
Copy-paste error from scatterplot code, plus missing trait.
> Fix selection alpha for line scatterplot

- chaco/tools/lasso_selection.py
Fixes #296.
Use `astype` to force boolean dtype for arrays before performing bitwise operations.
> Fix Lasso Selection for Newer Numpy

- chaco/ticks.py
Code was bad and buggy and not well motiviated.
@mdickinson care to review?
> Remove special-casing of powers of 2

- chaco/base.py
- chaco/lineplot.py
- chaco/tests/base_utils_test_case.py
This adds optimized numpy routines for detecting when intervals may intersect the visible range.  This significantly speeds up calculations for large datasets.
> Improved gather points for lineplots

- .travis.yml
- chaco/tests/arraydatasource_test_case.py
- chaco/tests/function_data_source_test_case.py
- chaco/tests/grid_data_source_test_case.py
- chaco/tests/image_data_test_case.py
- chaco/tests/jitterplot_test_case.py
- chaco/tests/line_scatterplot_test_case.py
- chaco/tests/multi_array_data_source_test_case.py
- chaco/tests/scatterplot_1d_test_case.py
- chaco/tests/test_colormapped_scatterplot.py
- chaco/tests/text_plot_1d_test_case.py
- travis-ci-requirements.txt
> Remove unittest2

- chaco/api.py
- chaco/axis.py
- chaco/tests/test_ticks.py
- chaco/ticks.py
- docs/source/user_manual/basic_elements/overlays.rst
- examples/demo/basic/minor_ticks_axis.py
Added `MinorPlotAxis`, which is a `PlotAxis` with smaller ticks, smaller interval, and no tick labels. This should not break anything, the only change was to `auto_interval()`, which I added an optional argument to.
This originated from the stackoverflow question here:
https://stackoverflow.com/questions/34755769/minor-ticks-in-chaco-plot/34833938#34833938
``` python
if __name__ == "__main__":
from traits.etsconfig.api import ETSConfig
ETSConfig.toolkit = 'qt4'
#
import warnings
warnings.filterwarnings(action = "ignore", category = FutureWarning, module="chaco")
warnings.filterwarnings(action = "ignore", category = FutureWarning, module="traits")
#
from PySide import QtGui, QtCore
import numpy as np
from enable.api import Component, Container, Window
from chaco.api import *
import sys
# …
```
> Added MinorPlotAxis

- CHANGES.txt
This adds entries in the changelog for the PRs that were merged since 4.5.0.
> DOC: Changelog entries.

- travis-ci-requirements.txt
Fixes #330. Use most recent releases of traits and traitsui.
> Use release versions of Traits and TraitsUI for CI tests

- .travis.yml
- chaco/contour/cntr.c
- chaco/tests/test_contour.py
Fix for the issue described in https://github.com/enthought/chaco/pull/328#issuecomment-264516430
@corranwebster Could you give this a review? I added some tests for the Contour class, too.
> Correct dtype for contour mask.

- setup.py
As in https://github.com/enthought/enable/pull/257
> Fix method for getting the _version.py file

- setup.py
- travis-ci-requirements.txt
> Release 4.6.0

- CHANGES.txt
Preparing for a quick 4.6.1 release.
> Update change log for 4.6.1

- CHANGES.txt
Release notes from the 4.6.1 release.
> DOC: Changes for 4.6.1

- chaco/plot.py
- chaco/tests/plot_test_case.py
> BUG: Fix use of itertools.chain()

- chaco/api.py
- chaco/plot_containers.py
This boilerplate was starting to multiply in product code. Added here, finally.
> ENH: Add a ConstraintsPlotContainer

- chaco/errorbar_plot.py
- chaco/tests/errorbarplot_test_case.py
> FIX: alias six.moves as sm

- chaco/overlays/api.py
- docs/source/user_manual/tools.rst
Includes a paragraph for:
* ImageInspector tool/overlay
* TextBoxOverlay
> Doc: Add documentation for 2 tools.

- chaco/overlays/databox.py
- chaco/overlays/tests/test_databox.py
Addresses issue #456 regarding disappearing image on DataBox resize, adds test.
> BUG: Fix DataBox resizing bug (#456)

- README.rst
Adding a mailing list section to the README to point to the `ETS users` mailing list.
> Add link to ETS google group.

- examples/demo/demo.py
Fixes #496 
Just needed to add a flag and turn the demo folder into a module
> Show contents of demo folder in TreeView

- examples/demo/noninteractive.py
> Fix empty string input error for python2.7 by reverting to raw_input

- chaco/colormapped_scatterplot.py
Removes some commented code in the color-mapped scatterplot.
> Remove commented code

- LICENSE.txt
> Update copyright year in license.txt

- README.rst
This PR removes the outdated coveralls coverage badge in the README file.
> Remove outdated coverage badge

- CHANGES.txt
targeting maint/5.0
This PR simply adds the most recent PR fixing chaco.axis to the changelog. 
After this minor PR is merged, I will open a PR that will be tagged as an rc2.
> add PR 772 to changelog 

- setup.py
The merge commit from this PR will be tagged as the second  release candidate
> Chaco Release Candidate 5.0.0rc2

- chaco/examples/demo/basic/minard_napoleon.py
- chaco/tests/test_arraydatasource.py
> Remove u prefixes as they are not needed on python 3

- .github/workflows/test-with-edm.yml
- .travis.yml
- appveyor.yml
- chaco/plots/tests/test_image_plot.py
- chaco/tests/test_plot.py
Part of https://github.com/enthought/ets/issues/57
This PR removes testing against pyqt4
> Remove pyqt from CI runs

- CHANGES.txt
- chaco/base_2d_plot.py
- chaco/base_xy_plot.py
- chaco/plot.py
- chaco/selectable_legend.py
- chaco/tests/test_array_or_none.py
- chaco/tools/image_inspector_tool.py
- chaco/tools/regression_lasso.py
This PR backports #786  to the `maint/5.0` branch in preparation for the 5.0 release. This PR also updates the changelog.
> Backport PR #786 and update changelog

- docs/source/annotated_examples.rst
- docs/source/user_manual/tutorial_hyetograph.rst
- docs/source/user_manual/tutorial_van_der_waal.rst
- setup.py
The merge commit from this PR will be tagged as the release. 
Note this PR also makes a few broken link fixes in the documentation before setting `IS_RELEASED` to True in the second commit.
> Chaco Release 5.0.0

- .github/workflows/test-with-edm.yml
- ci/edmtool.py
This PR removes the temporary changes introduced in https://github.com/enthought/chaco/pull/764
> Use enable from edm instead of git/github source

- .github/workflows/release-to-pypi.yml
- pyproject.toml
- setup.py
Need numpy and cython to build sdist due to setup.py requirements.  Need to specify the format of the long description.
Also try to trim down the platforms to those that have a numpy wheel available (building numpy under emulation is _painful_).
> Fix PyPI release script

- CHANGES.txt
Straightforward CHANGES.txt update.
> Update changelog for 5.1.0

- setup.py
> Set release flag

- examples/demo/advanced/spec_waterfall.py
Fix the FFT usage error in issue #872
> Fix fft error

- examples/tutorials/scipy2008/traits_example.py
as mentioned in issue #866, this is also caused by importing from an incorrect api. Fix by changing import. closes #866
> change marker_trait import

- chaco/axis.py
- chaco/examples/demo/basic/cmap_scatter.py
- chaco/examples/demo/basic/cmap_segment_plot.py
- chaco/examples/demo/basic/discrete_cmap_scatter.py
- chaco/examples/demo/basic/zoomable_colorbar.py
- chaco/examples/demo/data_labels.py
- chaco/label.py
- chaco/overlays/legend.py
- chaco/overlays/text_box_overlay.py
- chaco/overlays/text_grid_overlay.py
- chaco/overlays/tooltip.py
- chaco/plots/text_plot.py
- chaco/plots/text_plot_1d.py
- chaco/tools/regression_lasso.py
- docs/source/user_manual/basic_elements/overlays.rst
- examples/user_guide/plot_types/create_plot_snapshots.py
This should be equivalent for currently released Enable, but will keep things unchanged after [enable #977](https://github.com/enthought/enable/pull/977) is merged.
> Replace "modern" font with "sans-serif"

- chaco/tools/toolbars/toolbar_buttons.py
> Update usage of wx API

- CHANGES.txt
- setup.py
Update changelog and bump version number.
> Release 6.0.0
